
# tap repositories and their packages

tap caskroom/cask

tap homebrew/core
brew autoconf
brew automake
brew awscli
brew cairo
brew cmake
brew czmq
brew fontconfig
brew fontforge
brew freetype
brew gdbm
brew gettext
brew git --with-pcre
brew glib
brew go
brew gobject-introspection
brew groovy
brew harfbuzz
brew htop
brew httpie
brew icu4c
brew jpeg
brew jq
brew libevent
brew libffi
brew libpng
brew libsodium
brew libtiff
brew libtool
brew libxml2
brew lua
brew luajit
brew mas
brew mercurial
brew mysql
brew node
brew oniguruma
brew openssl
brew packer
brew pango
brew pcre
brew peco
brew pixman
brew pkg-config
brew psutils
brew python
brew python3
brew readline
brew redis
brew sqlite
brew terraform
brew tig
brew tmux
brew tree
brew v8
brew vim --with-lua --with-luajit --with-mzscheme --with-override-system-vi --with-python3 --with-tcl
brew watch
brew wget
brew xz
brew zeromq
brew zplug
brew zsh

tap homebrew/services

tap neovim/neovim
brew neovim

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 808647808 ActivityTimer
appstore 425264550 Blackmagic Disk Speed Test
appstore 411643860 DaisyDisk
appstore 1055511498 Day One
appstore 406056744 Evernote
appstore 467939042 Growl
appstore 555293879 KyPass Companion
appstore 539883307 LINE
appstore 430255202 Mactracker
appstore 992076693 MindNode
appstore 419330170 Moom
appstore 428834068 Night Owl
appstore 445189367 PopClip
appstore 880001334 Reeder
appstore 1035516352 ScanSnap Cloud
appstore 425955336 Skitch
appstore 803453959 Slack
appstore 494803304 WiFi Explorer
appstore 410628904 Wunderlist
appstore 497799835 Xcode
appstore 484757536 isHUD
